version: '3.8'

volumes:
  postgres-volume:

services:
  curry_addiction_nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: curry_addiction_nginx
    volumes:
      - ./laravel/:/var/www/html
    depends_on:
      - curry_addiction_php-fpm
    ports:
      - 38182:80

  curry_addiction_db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: curry_addiction_db
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: curry_addiction
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-volume:/var/lib/postgresql

  curry_addiction_php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: curry_addiction_php-fpm
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./laravel/:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - curry_addiction_db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=curry_addiction_db
      - DB_PORT=5432
      - DB_DATABASE=curry_addiction
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  curry_addiction_composer:
    container_name: curry_addiction_composer
    image: composer:2.1.6
    volumes:
      - ./laravel:/app
    entrypoint: composer

  curry_addiction_frontend-admin:
    build:
      context: ./
      dockerfile: ./docker/frontend-admin/Dockerfile
    container_name: curry_addiction_frontend-admin
    volumes:
      - ./frontend-admin:/app
    ports:
      - 8080:8080

  curry_addiction_frontend-user:
    build:
      context: ./
      dockerfile: ./docker/frontend-user/Dockerfile
    container_name: curry_addiction_frontend-user
    volumes:
      - ./frontend-user:/app
    ports:
      - 8081:8081